<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nz1uQpV' shared service.

return $this->privates['.service_locator.nz1uQpV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ServiceController::ajout' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\ServiceController::index' => ['privates', '.service_locator.Kk9u.DK', 'get_ServiceLocator_Kk9u_DKService.php', true],
    'App\\Controller\\ServiceController::suppression' => ['privates', '.service_locator.ucUh7eo', 'get_ServiceLocator_UcUh7eoService.php', true],
    'App\\Controller\\ServiceController:ajout' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\ServiceController:index' => ['privates', '.service_locator.Kk9u.DK', 'get_ServiceLocator_Kk9u_DKService.php', true],
    'App\\Controller\\ServiceController:suppression' => ['privates', '.service_locator.ucUh7eo', 'get_ServiceLocator_UcUh7eoService.php', true],
], [
    'App\\Controller\\ServiceController::ajout' => '?',
    'App\\Controller\\ServiceController::index' => '?',
    'App\\Controller\\ServiceController::suppression' => '?',
    'App\\Controller\\ServiceController:ajout' => '?',
    'App\\Controller\\ServiceController:index' => '?',
    'App\\Controller\\ServiceController:suppression' => '?',
]);
