<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqdnDiG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqdnDiG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqdnDiG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqdnDiG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIqdnDiG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IqdnDiG',
    'container.build_id' => 'e8818bfe',
    'container.build_time' => 1563091894,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqdnDiG');
